[tools]
go = "1.22"
python = "3.12"
node = "latest"

[task_config]
includes = [
  "tasks/project/mise.toml",
  "tasks/release/mise.toml",
  "tasks/setup/mise.toml",
  "tasks/build/mise.toml",
  "tasks/sdk/mise.toml",
  "tasks/test/mise.toml",
]
