[setup]
description = "Install project development dependencies"
usage = ""
run = "python ./tasks/setup/tasks.py setup"

[clean]
description = "Remove generated build and package artifacts"
usage = ""
run = "python ./tasks/setup/tasks.py clean"
