package main
import("context";"encoding/json";"fmt";"math";"os";"path/filepath";"time";"github.com/syugeeeeeeeeeei/BRIDGE/src/bridge/core";"github.com/syugeeeeeeeeeei/BRIDGE/src/bridge/gate";"github.com/syugeeeeeeeeeei/BRIDGE/src/bridge/ultrasound")
type GD struct{SchemaVersion string `json:"schema_version"`;ID string `json:"id"`;Directed bool `json:"directed"`;Nodes int `json:"nodes"`;Edges []gate.GraphEdge `json:"edges"`;DefaultQuery map[string]uint32 `json:"default_query"`}
type RS struct{Algorithm string `json:"algorithm"`;Status string `json:"status"`;Found bool `json:"found"`;Exact bool `json:"exact"`;Distance *float64 `json:"distance,omitempty"`;Path []uint32 `json:"path"`;Work core.WorkMetrics `json:"work"`;SolverTimeMS float64 `json:"solver_time_ms"`;EndToEndMS float64 `json:"end_to_end_time_ms"`;TracePath string `json:"trace_path"`;EventCount uint64 `json:"event_count"`}
func wj(p string,v any){b,e:=json.MarshalIndent(v,"","  ");if e!=nil{panic(e)};if e=os.WriteFile(p,append(b,'\n'),0644);e!=nil{panic(e)}}
func main(){out:="/mnt/data/compare6_adversarial";if len(os.Args)>1{out=os.Args[1]};os.MkdirAll(out,0755)
 const C=14;const L=30;const O=92; nodes:=2+O-1+C*(L-1); ns:=make([]gate.GraphNode,nodes);for i:=range ns{ns[i]=gate.GraphNode{ID:uint32(i)}};set:=func(i int,x,y float64){ns[i].X=&x;ns[i].Y=&y};set(0,0,0);set(1,100,0);es:=[]gate.GraphEdge{};add:=func(a,b int,w float64){es=append(es,gate.GraphEdge{From:uint32(a),To:uint32(b),Weight:w})}
 prev:=0;for i:=1;i<O;i++{id:=1+i;t:=float64(i)/O;set(id,100*t,38*math.Sin(math.Pi*t)+18);add(prev,id,.72);prev=id};add(prev,1,.72)
 base:=2+O-1; cn:=make([][]int,C);for c:=0;c<C;c++{cn[c]=make([]int,L-1);prev=0;for i:=1;i<L;i++{id:=base+c*(L-1)+i-1;cn[c][i-1]=id;t:=float64(i)/L;set(id,94*t,(float64(c)-6.5)*1.45+2.2*math.Sin(3*math.Pi*t+float64(c)));ww:=.22;if i>L-7{ww=.38};add(prev,id,ww);prev=id};add(prev,1,78+float64(c)*.7)}
 for c:=0;c<C-1;c++{for _,i:=range []int{9,14,19,23,26,28}{add(cn[c][i],cn[c+1][i],.08)}};for c:=0;c<C;c++{add(cn[c][20],cn[(c+3)%C][23],.15);add(cn[c][25],cn[(c+5)%C][27],.11)}
 gi:=gate.GraphInput{Type:"inline",Directed:false,Nodes:ns,Edges:es};wj(filepath.Join(out,"graph.json"),GD{"bridge.dataset.v1","heuristic-trap-multicorridor",false,nodes,es,map[string]uint32{"source":0,"target":1}})
 algs:=[]string{"dijkstra","bidirectional_dijkstra","astar","weighted_astar","bridge","anchor"};router:=gate.NewRouter();budget:=uint64(5_000_000);timeout:=float64(60_000);seed:=uint64(20260714);sums:=[]RS{}
 for _,a:=range algs{tp:=filepath.Join(out,a+".trace.jsonl");sink,e:=ultrasound.NewFileSink(tp,true);if e!=nil{panic(e)};col:=ultrasound.NewCollector("trace",sink);opts:=gate.RouteOptions{Observation:gate.ObservationOptions{Mode:gate.ObservationTrace,Observer:col,Reporter:col}};st:=time.Now();s:=RS{Algorithm:a,TracePath:tp}
  if a=="bridge"{r,e:=router.Route(context.Background(),gate.RouteRequest{SchemaVersion:gate.RouteRequestSchemaV1,RequestID:"adv-"+a,Graph:gi,Route:gate.RouteInput{Source:0,Target:1,Mode:core.ModeBalanced,Workers:1,Seed:seed},Budget:gate.BudgetInput{TotalWork:&budget,TimeoutMS:&timeout},Observation:gate.ObservationInput{Mode:gate.ObservationTrace}},opts);if e!=nil{panic(e)};s.Status=r.Status;s.Found=r.Found;s.Exact=r.Exact;s.Distance=r.Distance;s.Path=r.Path;s.Work=r.Work;s.SolverTimeMS=r.SolverTimeMS;s.EndToEndMS=r.TimeMS}else{r,e:=router.ExecuteOnce(context.Background(),gate.ExecuteRequest{SchemaVersion:gate.ExecuteRequestSchemaV1,RequestID:"adv-"+a,Target:gate.ExecuteTargetInput{ID:a},Graph:gi,Route:gate.RouteInput{Source:0,Target:1,Mode:core.ModeBalanced,Workers:1,Seed:seed},Budget:gate.BudgetInput{TotalWork:&budget,TimeoutMS:&timeout},Observation:gate.ObservationInput{Mode:gate.ObservationTrace}},opts);if e!=nil{panic(e)};s.Status=r.Status;s.Found=r.Found;s.Exact=r.Exact;s.Distance=r.Distance;s.Path=r.Path;s.Work=r.Work;s.SolverTimeMS=r.SolverTimeMS;s.EndToEndMS=r.EndToEndMS};col.Close(context.Background());s.EventCount=col.ObservationEventCount();if s.EndToEndMS==0{s.EndToEndMS=float64(time.Since(st).Nanoseconds())/1e6};wj(filepath.Join(out,a+".result.json"),s);sums=append(sums,s);fmt.Printf("%s cost=%v exact=%v work=%d time=%.3f events=%d path=%d\n",a,s.Distance,s.Exact,s.Work.TotalActions,s.EndToEndMS,s.EventCount,len(s.Path))}
 wj(filepath.Join(out,"benchmark_summary.json"),map[string]any{"schema_version":"bridge.simulation.comparison.v1","graph":"heuristic-trap-multicorridor","nodes":nodes,"edges":len(es),"seed":seed,"source":0,"target":1,"algorithms":sums})}
