from __future__ import annotations
from typing import Protocol
from ..core import SolverProgress, SolverTask, WorkBudget
from ..core import PathResult


class AnchorSession(Protocol):
    def run_slice(self, budget: WorkBudget) -> SolverProgress: ...
    def pause(self) -> object: ...
    def resume(self, state: object) -> None: ...
    def cancel(self) -> None: ...
    def result(self) -> PathResult | None: ...


class MainSolverPort(Protocol):
    def create_session(self, graph, request, task: SolverTask, observer) -> AnchorSession: ...
